server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:orchestrator-group}
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF